--- 
job-1: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    steps: 
      - checkout
      - 
        run: 
          command: "gradle test"
      - 
        store_test_results: 
          path: build/test-results
job-2: 
  - 
    run: 
      command: "gradle jar"
  - 
    store_artifacts: 
      destination: prefix
      path: build/libs
jobs: ~
version: 2.0
workflows: ~

